### ISSUE TITLE
anonymous vs named plugins

### ISSUE THREAD

**Issue by leviwheatcroft** [leviwheatcroft/metalsmith-debug-ui#2]
Plugins which return an anonymous function will be listed as 'anonymous' in debug-ui. The best way to fix this is to fix the plugins. I'll try to keep track of compatibility in this thread.

## compatible

* metalsmith-google-drive

## needs PR

 * metalsmith-collections

**Comment by jmatsushita** [comment]
Quite ugly, but given how many plugins are using this style (recommended in the official docs), here's a hack (which could maybe sit behind an option flag).

```
var stack = new Error().stack.split('\n').filter(line => !line.match('metalsmith-debug-ui'))
var [_,_, name = null ] = stack[1].match(/^(\s)*at.*\/(metalsmith-[^\/]*)/) || [];
```

If added in the `wrapped` [callback here](https://github.com/leviwheatcroft/metalsmith-debug-ui/blob/master/lib/index.js#L120), then the stacktrace contains the name of the original module.

Thanks for the plugin!

**Comment by leviwheatcroft** [comment]
Thanks! I'm open to this idea.

My first concern is there any chance this might break with different node versions, but if it's behind an option then devil may care I guess.

Secondly, this will only work where the plugin follows a pattern like `function metalsmith-whatever () { return function () {} }`, which I understand is the most common, but there will certainly be exceptions. That said, I note that if it doesn't work, this will just return 'anonymous' which is the current situation anyhow.

Re: official docs, can you refer me to the section in question? Maybe my opinion is flawed, but I don't see any good reason to return an anonymous function as the plugin instead of returning a named one. Most js code style guides discourage returning / exporting anonymous functions. 

Also, not sure if you noticed in the readme you can use `debugUi.report('stage 1')` or something to mark sections in the build process. It somewhat mitigates the problem, and at the time this seemed like a better solution than the alternatives.

**Comment by leviwheatcroft** [comment]
I've revisited this and the most recent commit contains the following as the wrapped function ...

```
        let wrapped = wrap(fn, (err) => {
          // we need to try to sniff the plugin name here, because it's likely
          // in the stack

          // regex to match a string like `/metalsmith-layouts/`
          let regex = /\/metalsmith-((?!debug-ui).*?)\//
          // apply to a stack trace (non-standard)
          let match = regex.exec(new Error().stack)
          if (match) fnName = match[1]
          // if that didn't work, try for a named function
          else if (fn.name) fnName = fn.name.replace(/bound /, '')
          // fall back to anonymous :(
          else fnName = 'anonymous'
          if (err) defer.reject(err)
          else defer.resolve()
        })
```

The regex I've used just looks for `/metalsmith-whatever/`, it's simple and I feel like it's reasonably robust, but I guess I'll find out.
It still falls back to looking for a named function (useful for custom, on-the-fly plugins), and finally coughs `anonymous`.

I'll probably publish this in the coming days.
