### ISSUE TITLE
Repeating stages when reloading 

### ISSUE THREAD

**Issue by david-genger** [leviwheatcroft/metalsmith-debug-ui#4]
I'm using metalsmith, webpack and browser-sync to reload my browser on each change, and with that, when my browser reloads it dioes not delete the old report only it adds to the old one. As you can see in this snip.

![capture](https://user-images.githubusercontent.com/12090146/33288982-fb2b4e74-d38b-11e7-988a-2e3d68d3f3d3.PNG)

**Comment by leviwheatcroft** [comment]
Hey, I'd need to see your metalsmith build file to really understand what's going on or how to resolve it.

I suspect that you'll need a function with which to clear debug-ui's history every time your metalsmith build runs. I'd be happy to add that and it would be easy to do.

But yeah, before I do that if I could see your build script just to understand exactly what's happening.

**Comment by david-genger** [comment]
Thanks for replying!

I suspect it has something to so with this https://github.com/segmentio/metalsmith-collections/pull/48
I would need the variable name in order to clear it.
```
.use((files, metalsmith, done) => {
    metalsmith._metadata.collections = null
    metalsmith._metadata.posts = null
    `metalsmith._metadata.debugUi= null` // ??
    done()
  })
```

**Comment by leviwheatcroft** [comment]
Hmm... yeah debug-ui doesn't store this history in `metalsmith._metadata`, it's stored privately. 

I'll take a look and see what the best way to resolve this might be. It will be a few days before I get to it.

**Comment by leviwheatcroft** [comment]
I just pushed a new version 0.3.0 to npm, install with `npm i metalsmith-debug-ui@0.3.0`. 

It includes a `clear` function... so you should be able to:

```
import debugUi from 'metalsmith-debug-ui'
// ...
.use((files, metalsmith) => { // no need for `done` with async code
    metalsmith._metadata.collections = null
    metalsmith._metadata.posts = null
    debugUi.clear()
  })
```

This version seems to work in my projects but I've not tested with `metalsmith-browser-sync` so I'll leave this issue open for now.

**Comment by david-genger** [comment]
This issue did not get fixed, but thanks for your effort.

**Comment by leviwheatcroft** [comment]
Ok, I need some more information so I can understand what's actually happening. Can you post your whole build file ?

**Comment by david-genger** [comment]
`export default new Metalsmith(paths.projectRoot)
  .clean(__PROD__)
  .source(paths.metalsmithSource)
  .destination(paths.metalsmithDestination)
  .use(
    assets({
      source: "./src/assets",
      destination: "./assets"
    })
  )
  .use(
    markdown({
      html: true
    })
  )
  .use(
    prismic({
      url: "https://test.cdn.prismic.io/api" //fake API
    })
  )
  .use((files, metalsmith, done) => { //clearing the collenctions
    metalsmith._metadata.collections = null
    metalsmith._metadata.exhibit = null
    console.log(metalsmith)
    done()
  })
  .use(report('before collection'))
  .use(
    collections({
      exhibit: {
        pattern: "exhibit_page/*.hbs",
        sortBy: "date",
        reverse: true
      }
    })
  )
  .use(report('after collection'))
  .use(pagination({
    'collections.exhibit': {
      perPage: 2,
      template: 'exhibit.hbs',
      first: 'exhibit/index.html',
      path: 'exhibit/:num/index.html'
    }
  }))
  .use(report('after pagination'))
  .use(
    metalsmithInPlace({
      engineOptions: {
        helpers: { }
      }
    })
  )
  .use(
    permalinks({
      relative: false
    })
  )
  .use(
    layouts({
      engine: "handlebars",
      default: "default.hbs",
      directory: "src/layouts/layout-templates",
      partials: "src/layouts/partials",
      helpers: {
        helpers: helpers
      },
      remane: true
    })
  )
  .use(report('Done'))`

**Comment by leviwheatcroft** [comment]
It doesn't look like you've actually called the `clear` fn I added?

So you need to `import { report, clear } from 'metalsmith-debug-ui'` and then make the `clearing the collections section like this:

```
.use((files, metalsmith, done) => { 
  //clearing the collenctions 
  metalsmith._metadata.collections = null 
  metalsmith._metadata.exhibit = null
  clear()
  console.log(metalsmith) 
  done() 
  }) 
```

**Comment by david-genger** [comment]
I see, will do so soon, and I’ll let you know. Thanks! 🙏

________________________________

**Comment by leviwheatcroft** [comment]
How did you go with this ? any luck ?

**Comment by leviwheatcroft** [comment]
Just tidying up this repo, feel free to reopen if this isn't resolved.
