### ISSUE TITLE
How to use it in metalsmith.json?

### ISSUE THREAD

**Issue by maximelebreton** [leviwheatcroft/metalsmith-debug-ui#8]
Hello, how can I use it in `metalsmith.json`?

When I try to using it like a classic plugin
```json
{
    "source": "src/pages/",
    "destination": "dist/",
    "clean": false,
    "plugins": {
      "metalsmith-debug-ui": {}
    }
}
```

It throws an error: `mod is not a function`

Thanks!

**Comment by leviwheatcroft** [comment]
Sorry metalsmith-debug-ui won't work with json mode in the same way as other plugins.

As a workaround you could try a custom plugin to patch the metalsmith instance. I haven't tried this and honestly not sure if it will work.

debugUiPatch.js:
```
var debugUi = require('metalsmith-debug-ui')

module.exports = function (metalsmith) {
  debugUi.patch(metalsmith)
}
```
Then in metalsmith.json
```
{
    "source": "src/pages/",
    "destination": "dist/",
    "clean": false,
    "plugins": {
      "./debugUiPatch.js": {}
    }
}
```

In any case, I'll update the readme to say that this plugin isn't compatible with `metalsmith.json` mode.
